version: '3.1'

services:
  db:
    image: mysql
    container_name: my-mysql
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9977:3306"